{{
    config(materialized='table'
)}}


select 
DATE::timestamp as DATE
,PROVINCE
,TOTAL_CASES
,TOTAL_DEATHS_PER_MILLION
,TOTAL_DEATHS
,TOTAL_RECOVERED
,CASE_FATALITY_RATE
,CASE_RECOVERED_RATE
from  "FIVETRAN_INTERVIEW_DB"."GOOGLE_SHEETS"."COVID_19_INDONESIA_SURYA_SRINIVASAN" 
where ISLAND is not null 